services:
  db:
    image: postgres:16
    container_name: nova_lance_db
    restart: always
    environment:
      POSTGRES_DB: nova_lance_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nova_lance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nova_lance_api
    privileged: true
    volumes:
      - .:/rails_api
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
      - "1234:1234"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      TZ: "Asia/Tokyo"
      EDITOR: "code --wait"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nova_lance_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  nova_lance_network:
    driver: bridge
