name: Test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and cache gems for API
        uses: ruby/setup-ruby@v1
        with:
          working-directory: .
          bundler-cache: true

      - name: Run tests (parallel)
        working-directory: .
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5433/nova_lance_test
          DEVISE_JWT_SECRET_KEY: test_jwt_secret_key_for_github_actions
          SECRET_KEY_BASE: test_secret_key_base_for_github_actions
        run: |
          bundle exec rails db:prepare
          PARALLEL_COUNT=${GITHUB_RUNNER_CPU_COUNT:-2}
          bundle exec parallel_rspec -n $PARALLEL_COUNT spec

      - name: Upload coverage report
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
